"""B5 — cross-formalism differential invariants.

Paired/property tests that pin relationships *between* PyPhi's formalisms, the
dominant correctness strategy across the 5+ formalisms. Two candidate
invariants from the roadmap are examined here:

  - **``phi_2026 <= phi_2023`` (holds).** The 2026 formalism adds the Eq. 23
    intrinsic-information cap, which can only lower system phi (cf. B4). A
    Hypothesis property over random small substrates confirms it, generalizing
    B4's per-network check. Its corollary — 2023-reducible implies
    2026-reducible — follows immediately.

  - **"IIT 3.0 and 4.0 agree on reducibility" (REFUTED).** Empirically the two
    formalisms disagree on ~70% of random reachable small substrates (audit
    2026-06-13):
    IIT 3.0 (EMD over constellations) frequently finds ``phi > 0`` where IIT
    4.0 (GID system integration) finds ``phi = 0``. ``test_iit3_iit4_*`` pins a
    concrete 2-node witness so this divergence is documented and locked, not
    silently assumed.

  - **4.0 non-regression against the ``b3aaa3e5`` pre-refactor oracle
    (holds).** ``TestPreRefactorByteMatch`` recomputes system phi for a fixed
    corpus of small substrates and asserts it matches the values computed at
    commit ``b3aaa3e5`` — locking the 2.0 refactor as non-regressing for the
    IIT 4.0 (2023) hot path. The oracle is generated by
    ``scripts/gen_iit4_2023_byte_match_oracle.py`` (run once against a worktree
    of that commit) and stored in
    ``test/data/iit4_2023_byte_match_oracle.json`` (inputs + expected phi, so
    the test is self-contained). The match uses the ``DIRECTED_BIPARTITION``
    system scheme (the oracle's ``DIRECTED_BI``), which is *preserved* across
    the refactor; the default ``SET_UNI/BI`` scheme is intentionally excluded —
    it was deliberately replaced by ``DIRECTED_SET_PARTITION`` (a real
    numerical change, per the N1 paper-faithful fix), so it is not a
    non-regression target.

    Two findings from running the oracle made a *literal* byte (``float.hex()``)
    match infeasible — both expected, neither a regression:

    1. **The pre-refactor ``phi`` was the raw, un-clamped integration.** Where
       the minimum-over-partitions integration is negative ("preventative
       cause" structure), ``b3aaa3e5`` reported that negative value as ``phi``;
       the refactor correctly applies the Eqs. 19-20 ``|·|+`` clamp, exposing
       ``phi = max(0, raw)`` and preserving the raw value on ``signed_phi``.
       The genuine non-regression target is therefore HEAD's ``signed_phi``,
       which reproduces the oracle's raw ``phi`` (and HEAD's clamped ``phi``
       reproduces ``max(0, oracle)``).
    2. **Sub-ULP floating-point reassociation.** Across the refactor (and the
       intervening dependency drift) the positive values agree only to ~1 ULP
       (max abs diff ``3.3e-16`` over the corpus), not bit-for-bit. The test
       asserts machine-epsilon equivalence (``atol=1e-12``, ~3000x the observed
       noise floor — tight enough to catch any real algorithmic change).

Deferred slices of B5 (follow-ons): the AC/IIT sign-agreement invariant
(actual causation is a separate subsystem with an unsettled cross-formalism
relation). A 3.0 byte-match is not viable from ``b3aaa3e5`` — its
``compute.phi`` is not a valid IIT 3.0 SIA (basic -> 0) — so it would need a
genuine PyPhi 1.x oracle.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest
from hypothesis import assume
from hypothesis import given
from hypothesis import settings
from hypothesis import strategies as st

from pyphi import Substrate
from pyphi import System
from pyphi.conf import config
from pyphi.conf import presets
from pyphi.conf.formalism import IITConfig
from pyphi.formalism import iit3

from .hypothesis_utils import binary_state
from .hypothesis_utils import small_substrate

_ZERO = 1e-9

_ORACLE_PATH = Path(__file__).parent / "data" / "iit4_2023_byte_match_oracle.json"


def _iit4_phi(substrate: Substrate, state: tuple[int, ...], preset: dict) -> float:
    """System phi via the active IIT 4.0 formalism (``System.sia``)."""
    with config.override(**preset, validate_system_states=False):
        return float(System(substrate, state).sia().phi)


def _iit3_phi(substrate: Substrate, state: tuple[int, ...]) -> float:
    """System phi via the genuine IIT 3.0 SIA (``System.sia`` is 4.0-only)."""
    with config.override(**presets.iit3, validate_system_states=False):
        return float(iit3.sia(System(substrate, state)).phi)


class TestCapMonotonicityAcrossVersions:
    """The 2026 ii(s) cap never raises system phi above the 2023 value."""

    @settings(max_examples=30, deadline=None)
    @given(data=st.data())
    def test_phi_2026_le_phi_2023(self, data) -> None:
        substrate = data.draw(small_substrate())
        state = data.draw(binary_state(substrate.size))
        try:
            phi_2023 = _iit4_phi(substrate, state, presets.iit4_2023)
            phi_2026 = _iit4_phi(substrate, state, presets.iit4_2026)
        except Exception:
            assume(False)
            return
        assert phi_2026 <= phi_2023 + _ZERO, (
            f"2026 cap raised phi above 2023: phi_2026={phi_2026} > "
            f"phi_2023={phi_2023} (state={state})"
        )

    def test_phi_2026_le_phi_2023_regression(self) -> None:
        """Deterministic guard for the Eq-23 cap MIP-selection bug.

        A 2-node substrate where the per-partition cap once shifted the system
        MIP and produced ``phi_2026 > phi_2023`` (0.301 vs 0.172). With the cap
        applied to the 4.0-selected MIP, the cap can only lower phi.
        """
        substrate = Substrate(
            np.array([[0.0, 0.75], [0.5, 0.5], [0.75, 0.25], [0.0, 0.75]]),
            cm=np.ones((2, 2), dtype=int),
        )
        state = (0, 1)
        phi_2023 = _iit4_phi(substrate, state, presets.iit4_2023)
        phi_2026 = _iit4_phi(substrate, state, presets.iit4_2026)
        assert phi_2026 <= phi_2023 + _ZERO, (
            f"cap regression: phi_2026={phi_2026} > phi_2023={phi_2023}"
        )


class TestReducibilityDivergence:
    """IIT 3.0 and IIT 4.0 do NOT agree on reducibility — pinned witness."""

    # 2-node substrate (state-by-node TPM, fully connected) at state (0, 0)
    # where IIT 3.0 finds phi > 0 but IIT 4.0 (2023) finds phi = 0. Found by
    # the 2026-06-13 cross-formalism audit; locked here so the divergence is
    # documented rather than silently assumed away.
    _TPM = np.array([[1.0, 0.75], [0.75, 1.0], [0.5, 0.75], [1.0, 0.25]])
    _STATE = (0, 0)

    @pytest.mark.emd
    def test_iit3_irreducible_where_iit4_reducible(self) -> None:
        substrate = Substrate(self._TPM, cm=np.ones((2, 2), dtype=int))
        phi_3 = _iit3_phi(substrate, self._STATE)
        phi_4 = _iit4_phi(substrate, self._STATE, presets.iit4_2023)
        assert phi_3 > 1e-3, f"expected IIT 3.0 phi > 0, got {phi_3}"
        assert phi_4 < _ZERO, f"expected IIT 4.0 phi = 0, got {phi_4}"


_BYTE_MATCH_ATOL = 1e-12


def _load_oracle() -> dict:
    return json.loads(_ORACLE_PATH.read_text())


def _iit4_2023_dbi_sia(tpm: list, cm: list, state: tuple[int, ...]):
    """SIA under IIT 4.0 (2023) with the refactor-preserved DIRECTED_BIPARTITION
    scheme — the current-code analogue of the oracle's config."""
    substrate = Substrate(np.array(tpm), cm=np.array(cm))
    override = {
        # All non-listed fields default to the oracle's values (GID measures,
        # precision 13, shortcircuit on); only the partition scheme is pinned
        # to the preserved DIRECTED_BIPARTITION (== oracle's DIRECTED_BI).
        "iit": IITConfig(
            version="IIT_4_0_2023",
            system_partition_scheme="DIRECTED_BIPARTITION",
        ),
        "validate_system_states": False,
    }
    with config.override(**override):
        return System(substrate, tuple(state)).sia()


class TestPreRefactorByteMatch:
    """IIT 4.0 (2023) system phi reproduces the ``b3aaa3e5`` pre-refactor oracle.

    Locks the 2.0 refactor as numerically non-regressing on the 4.0 hot path:
    any algorithmic drift in the directed-bipartition SIA shows up as a phi
    mismatch beyond machine epsilon. The corpus (48 small-substrate states, 20
    with nonzero raw phi spanning positive complexes and negative "preventative
    cause" systems) and its expected values live in
    ``test/data/iit4_2023_byte_match_oracle.json``.

    The oracle's ``phi`` is the *raw* (un-clamped) integration, so it is
    compared against HEAD's ``signed_phi``; HEAD's clamped ``phi`` is separately
    asserted to equal ``max(0, oracle)`` (the Eqs. 19-20 ``|·|+`` correction the
    refactor added). See the module docstring for why a literal ``float.hex()``
    match is infeasible.
    """

    _oracle = _load_oracle()
    _records = _oracle["records"]

    def test_oracle_metadata(self) -> None:
        assert self._oracle["oracle_commit"].startswith("b3aaa3e5")
        assert self._oracle["formalism"] == "IIT_4_0_2023"
        # Guard against an accidentally trivial (all-zero) corpus.
        nonzero = sum(1 for r in self._records if abs(r["phi"]) > _ZERO)
        assert nonzero >= 15, f"expected a nontrivial corpus, got {nonzero} nonzero"

    @pytest.mark.parametrize(
        "record",
        _records,
        ids=[r["name"] for r in _records],
    )
    def test_phi_byte_match(self, record: dict) -> None:
        sia = _iit4_2023_dbi_sia(record["tpm"], record["cm"], record["state"])

        # The genuine non-regression target: HEAD's raw integration reproduces
        # the oracle's (also-raw) phi to machine epsilon.
        got_signed = float(sia.signed_phi)
        assert got_signed == pytest.approx(record["phi"], abs=_BYTE_MATCH_ATOL), (
            f"{record['name']}: signed_phi {got_signed!r} != oracle "
            f"{record['phi']!r} (Δ={got_signed - record['phi']:.3e})"
        )
        got_signed_norm = float(sia.signed_normalized_phi)
        assert got_signed_norm == pytest.approx(
            record["normalized_phi"], abs=_BYTE_MATCH_ATOL
        ), (
            f"{record['name']}: signed_normalized_phi {got_signed_norm!r} != "
            f"oracle {record['normalized_phi']!r}"
        )

        # The one intended behavioral change: the clamped phi is max(0, raw).
        got_phi = float(sia.phi)
        assert got_phi == pytest.approx(
            max(0.0, record["phi"]), abs=_BYTE_MATCH_ATOL
        ), f"{record['name']}: clamped phi {got_phi!r} != max(0, {record['phi']!r})"
        got_norm = float(sia.normalized_phi)
        assert got_norm == pytest.approx(
            max(0.0, record["normalized_phi"]), abs=_BYTE_MATCH_ATOL
        ), (
            f"{record['name']}: clamped normalized_phi {got_norm!r} != "
            f"max(0, {record['normalized_phi']!r})"
        )
