language: python

sudo: false

branches:
  only:
      - master
      - develop

# Setup databases
services:
  - mongodb  # port 27017 (default)
  - redis-server  # port 6379 (default)

python:
  - "3.4"
  - "3.5"
  - "3.6"

# Setup miniconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - pip install -r requirements.txt
  - pip install coveralls
  - pip freeze

# Run tests
script: coverage run --source=pyphi -m py.test --slow

after_success: coveralls

notifications:
  email: false
  slack:
    rooms:
         secure: "C6PSvK/FEmyD+S71VVzS29NZpD9CFI/f3UMjc6i08xYHjFNMZUplfHyUqNLNqgVVBsKR1En4B8ryuriEnM8wwZzCVdxjh7HDsx8aNE2z1XG5tkqoRP4ppNfqNaYRoMcSZFW89DfVNbIVDM11wKXL7/YnRCmlJy0p1NtKzlncXCM="
    on_success: never
    on_failure: always
