"""Anchor both background conventions to the PyPhi 1.2.0 oracle.

The oracle JSON is generated by ``scripts/gen_iit3_background_oracle.py``
from a genuine PyPhi 1.2.0 install; see ``test/data/iit3-canonical/``.
"""

import json
from pathlib import Path

import pytest

import pyphi
from pyphi import config
from pyphi.conf import presets
from pyphi.formalism import iit3
from pyphi.system import System
from test import example_substrates

pytestmark = pytest.mark.emd

ORACLE_PATH = (
    Path(__file__).parent.parent
    / "data"
    / "iit3-canonical"
    / "background_conditioning_oracle.json"
)


@pytest.fixture(scope="module")
def oracle():
    with ORACLE_PATH.open() as f:
        return json.load(f)


@pytest.fixture()
def system():
    return System(
        example_substrates.noisy_or_background_substrate(),
        (1, 0, 0),
        node_indices=(0, 1),
    )


class TestRepertoireLevel:
    def test_conditioned_cause_repertoire_matches_1x(self, oracle, system):
        with config.override(**presets.iit3):
            rep = system.cause_repertoire((0,), (1,)).squeeze()
        assert rep == pytest.approx(oracle["cause_repertoire"]["observed"])

    def test_marginalized_cause_repertoire_matches_eq4(self, oracle, system):
        with (
            config.override(**presets.iit3),
            config.override(background_conditioning="CAUSAL_MARGINALIZATION"),
        ):
            rep = system.cause_repertoire((0,), (1,)).squeeze()
        assert rep == pytest.approx(
            oracle["cause_repertoire"]["predicted_eq4_marginalized"]
        )

    def test_effect_repertoire_matches_both_conventions(self, oracle, system):
        expected = oracle["effect_repertoire"]["observed"]
        for value in ("CAUSAL_MARGINALIZATION", "CONDITION_CURRENT_STATE"):
            with config.override(background_conditioning=value):
                rep = system.effect_repertoire((0,), (1,)).squeeze()
            assert rep == pytest.approx(expected)


class TestEndToEnd:
    def test_conditioned_phi_matches_1x(self, oracle, system):
        with config.override(**presets.iit3, progress_bars=False):
            phi = float(iit3.sia(system).phi)
        assert phi == pytest.approx(oracle["sia"]["phi"], abs=1e-6)

    def test_marginalized_phi_differs_and_is_pinned(self, system):
        with (
            config.override(**presets.iit3, progress_bars=False),
            config.override(background_conditioning="CAUSAL_MARGINALIZATION"),
        ):
            phi = float(iit3.sia(system).phi)
        assert phi == pytest.approx(0.41607, abs=1e-6)

    def test_basic_subset_phis_match_1x(self, oracle):
        basic = pyphi.examples.basic_substrate()
        with config.override(**presets.iit3, progress_bars=False):
            for key, expected in oracle["basic_network_subsets"].items():
                nodes = tuple(int(x) for x in key.strip("()").split(",") if x.strip())
                system = System(basic, (1, 0, 0), node_indices=nodes)
                phi = float(iit3.sia(system).phi)
                # rel, not abs: the (0, 1, 2) full-substrate EMD sum carries
                # the same ~1e-6 floating-point residual as the 2.3125
                # canonical value elsewhere in the suite (e.g.
                # test/formalism/test_complexes.py), which compares it with
                # the same tolerance.
                assert phi == pytest.approx(expected["phi"], rel=1e-6), key
